### PR TITLE
Body Parser: Up parsing limit

### PR DESCRIPTION
**Pull request by jarstelfox**

### CODE REVIEW

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :fish: through 5369167

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by mlahargou** [comment]
CR 📱

**Review by djmetzle — APPROVED** [review]
CR :gear:

**Comment by ardelato** [comment]
I don't have permissions to add labels, but I am currently QAing

**Comment by davidrans** [comment]
CR ☕

**Comment by ardelato** [comment]
QA 👍 

Not really sure what else I can do to validate this:

## Steps Taken:
1. Git cloned this repo on my Cominor home directory
2. Checked out Jared's changes by using `gh pr checkout 118` since its code changes from a fork
3. I then ran `npm install`
4. I then ran `npm test` and all tests passed

**Pull request merged**
