### PR TITLE
git-build: Add html output support

### PR DESCRIPTION
**Pull request by mlahargou**
If we pass in a `printHtml` config option, we surround the text
with `<pre>...</pre>` tags which signify preformatted text.

It's simple and should get the job done.

Also, updated the sample config.

Closes https://github.com/danielbeardsley/cimpler/issues/108

### CODE REVIEW

**Comment by mlahargou** [comment]
Not sure if I should go with this approach where each time we want to write we do this or just have everything before the exec be in one `<pre>` block and everything at the end be in one `<pre>` block.  Thoughts?

**Comment by mlahargou** [comment]
I'm getting something like this: 
```
<pre>----------------------------------------------
 Cimpler build started at: Mon Jan 18 2021 15:36:05 GMT-0700 (MST) time in queue: 0min
----------------------------------------------
</pre>
<pre>
Merge Successful
</pre>
+ cd /home/ci-coverage/Code/
+ php Tests/Exec/PullRequestCoverage.php
<ul>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/Admin/UI/Coupons/index.php.html'>Admin/UI/Coupons/index.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/Libs/UrlLocalizer.php.html'>Libs/UrlLocalizer.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/Tests/Exec/PullRequestCoverage.php.html'>Tests/Exec/PullRequestCoverage.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/Tests/Integration/Cart/ProductsToShopifyJobTest.php.html'>Tests/Integration/Cart/ProductsToShopifyJobTest.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/Tests/Integration/Cart/ShopifyWebhookProductBodyFactoryTest.php.html'>Tests/Integration/Cart/ShopifyWebhookProductBodyFactoryTest.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/iFixit/Admin/Akeneo/ApiProductExportJob.php.html'>iFixit/Admin/Akeneo/ApiProductExportJob.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/iFixit/Admin/Akeneo/ProductsToShopifyJob.php.html'>iFixit/Admin/Akeneo/ProductsToShopifyJob.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/iFixit/Cart/Order/Coupon/LiveObject/Coupon.php.html'>iFixit/Cart/Order/Coupon/LiveObject/Coupon.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/iFixit/Framework/Assets/WebpackBuild.php.html'>iFixit/Framework/Assets/WebpackBuild.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/iFixit/Generic/Pages/Components/RepairAssociationBanner.php.html'>iFixit/Generic/Pages/Components/RepairAssociationBanner.php</a></li>
<li><a href='https://www.ubreakit.com/Misc/coverage-log/current/iFixit/Service/ShopifyWebhook/ProductBodyFactory.php.html'>iFixit/Service/ShopifyWebhook/ProductBodyFactory.php</a></li>
</ul>
<pre>
-------------------------------------------
 Cimpler build finished in 7 seconds
 Status: success Exit Code: 0
-------------------------------------------
</pre>
```

Which renders pretty nice:
image

---
The only problem is the exec command is printing the commands it is running (i.e. `cd /home/ci-coverage/Code/`) in the child process which gets piped to the log file. Is there any way I could have the child process not print out the commands? Then I could just print them in cimpler?

**Comment by mlahargou** [comment]
I just surrounded the whole file in `pre` tags which looks better:
https://www.ubreakit.com/Misc/cimpler-logs/coverage/coverage-show-coverage-report-on-pr--23c39ba2bd9e5d074f47af75ec07b2f837386593--1611009365709.log

image

**Comment by danielbeardsley** [comment]
> I just surrounded the whole file in `pre` tags which looks better:

But then the script in question doesn't get a chance to easily *not* be in a `<pre>`. I'd vote for leaving it how it was.

**Comment by danielbeardsley** [comment]
I vote for dropping the `set -x` in `git-build`. Perhaps it was meant for that to be a `set -e` all long? The commit history didn't indicate the `set -x` was intentional.

**Comment by mlahargou** [comment]
I think that looks great! Thanks Danny!
image

**Comment by danielbeardsley** [comment]
CR 👍

**Comment by BaseInfinity** [comment]
CR 👙  Awesome!

**Pull request merged**
